#TEST ENVIRONEMNT SETTING#
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql-instance1.sovanmaws.us-east-1.rds.amazonaws.com:3306/profiles
    username: <USERNAME>
    password: <SECRET>